name: Publish to AMO

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: npm run build

    - name: Zip the extension
      run: zip -r cutefasti_url_shortener-autobuild${{ github.run_number }}.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: dist/*.xpi

    - name: Create GitHub Release 
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.xpi

    - name: Upload to AMO
      uses: birchill/amo-upload@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        addon_id: cute-fasti-url-shortener
        amo_jwt_iss: ${{ secrets.AMO_JWT_ISS }}
        amo_jwt_secret: ${{ secrets.AMO_JWT_SECRET }}
        addon_file: cutefasti_url_shortener-autobuild${{ github.run_number }}.zip
        release_notes: 'Automated release from GitHub Actions workflow. Version: ${{ github.run_number }}.'